version: '3.4'

services:
  # database:
  #   image: postgres:14-alpine
  #   container_name: postgres
  #   volumes:
  #     - postgresvolumes:/pgdata
  #   networks:
  #     - private
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - ${PORT}:3000